// <auto-generated />
using System;
using Aumatizador;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Aumatizador.Migrations
{
    [DbContext(typeof(BancoEstatistica))]
    partial class BancoEstatisticaModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Aumatizador.Estatisica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("horarioFim")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("horarioInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("iteracao")
                        .HasColumnType("integer");

                    b.Property<string>("setup")
                        .HasColumnType("text");

                    b.Property<string>("tipo")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("estatisticas");
                });
#pragma warning restore 612, 618
        }
    }
}
